feat: Don't break on AttributeError
It's possible that a valid feed is sometimes not valid, due to a validation page with an http redirect. Such a page will trigger `object has no attribute 'link'` errors.